# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  apigateway:
    build:
      context: "C:\\Code Projects\\InnerTrader"
      dockerfile: "ApiGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/ApiGateway.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
    image: "apigateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\OnurI\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Code Projects\\InnerTrader\\ApiGateway:/app:rw"
    - "C:\\Code Projects\\InnerTrader:/src:rw"
    working_dir: "/app"
  blogapi:
    build:
      context: "C:\\Code Projects\\InnerTrader"
      dockerfile: "BlogAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/BlogAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
    image: "blogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\OnurI\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Code Projects\\InnerTrader\\BlogAPI:/app:rw"
    - "C:\\Code Projects\\InnerTrader:/src:rw"
    working_dir: "/app"
  engagementsapi:
    build:
      context: "C:\\Code Projects\\InnerTrader"
      dockerfile: "EngagementsAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/EngagementsAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
    image: "engagementsapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\OnurI\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Code Projects\\InnerTrader\\EngagementsAPI:/app:rw"
    - "C:\\Code Projects\\InnerTrader:/src:rw"
    working_dir: "/app"
  usersystemapi:
    build:
      context: "C:\\Code Projects\\InnerTrader"
      dockerfile: "UserSystemAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/UserSystemAPI.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net6.0/UserSystemAPI.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\OnurI\\.nuget\\packages"
    image: "usersystemapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\OnurI\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Code Projects\\InnerTrader\\UserSystemAPI:/app:rw"
    - "C:\\Code Projects\\InnerTrader:/src:rw"
    working_dir: "/app"
